plugins { id 'com.android.application' }

android {
    namespace 'com.melody.player'
    compileSdk 35

    defaultConfig {
        applicationId 'com.melody.player'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '1.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
