plugins { id 'com.android.application' }

android {
    namespace 'com.melody.player'
    compileSdk 35

    defaultConfig {
        applicationId 'com.melody.player'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '1.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
plugins { id 'com.android.application' }

android {
    namespace 'com.melody.player'
    compileSdk 35

    defaultConfig {
        applicationId 'com.melody.player'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '1.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
